# Generated by Django 4.1.4 on 2023-01-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_task_master',
            name='priority',
            field=models.CharField(choices=[('Urgent', 'Urgent'), ('Important', 'Important'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sub_space_master',
            name='priority',
            field=models.CharField(choices=[('Urgent', 'Urgent'), ('Important', 'Important'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sub_tasks',
            name='priority',
            field=models.CharField(choices=[('Urgent', 'Urgent'), ('Important', 'Important'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50, null=True),
        ),
    ]
