# Generated by Django 4.1.4 on 2023-01-30 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_add_task_master_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_tasks',
            name='dynamic_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sub_tasks',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtask_group_id', to='my_app.space_master'),
        ),
        migrations.AddField(
            model_name='sub_tasks',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_task_projectid', to='my_app.sub_space_master'),
        ),
        migrations.AddField(
            model_name='sub_tasks',
            name='task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_task_taskid', to='my_app.add_task_master'),
        ),
    ]
