# Generated by Django 4.1.4 on 2023-02-15 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_sub_space_attachment_text_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_user_access_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('project_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Project_user_access_link_project_id', to='my_app.sub_space_master')),
            ],
        ),
    ]
