# Generated by Django 4.1.4 on 2023-02-15 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0005_remove_space_view_access_user_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_space_master',
            name='sub_space_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_space_master_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
