# Generated by Django 4.1.4 on 2023-02-06 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_add_task_master_parent_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sub_tasks',
        ),
    ]
