# Generated by Django 4.1.4 on 2023-02-16 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_sub_space_master_sub_space_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_space_checklist',
            name='due_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='sub_space_access_permission',
        ),
    ]
