# Generated by Django 4.1.4 on 2023-02-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_sub_space_checklist_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_space_checklist',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
