# Generated by Django 4.1.4 on 2023-02-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_delete_sub_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_task_master',
            name='task_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
