# Generated by Django 4.1.4 on 2023-02-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_alter_sub_space_checklist_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_task_attachment',
            name='text_content',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
