# Generated by Django 4.1.4 on 2023-02-08 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0008_add_task_master_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_space_attachment',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_space_auth_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
