# Generated by Django 4.1.4 on 2023-02-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_add_task_master_tag_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_task_checklist',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
