# Generated by Django 4.1.4 on 2023-02-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_add_task_master_invite_user_auth_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_task_access_user',
        ),
    ]
