# Generated by Django 4.1.4 on 2023-02-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_add_task_master_multiple_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_task_master',
            name='multiple_parent_id',
            field=models.ManyToManyField(blank=True, related_name='Add_task_master_parent_many_to_many', to='my_app.add_task_master'),
        ),
    ]
